### ISSUE TITLE
Errno 104 Connection reset by peer

### ISSUE THREAD

**Issue by dyollluap** [BD2KGenomics/s3am#47]
I've had this working just fine throughout the day, even on same worker 10 minutes ago. Using Arjun's script to upload a single fastq.gz from an ec2 machine. 

It loops through this error for a while

```
2016-03-30 02:13:39,556 operations(11106) Traceback (most recent call last):
  File "/opt/s3am/local/lib/python2.7/site-packages/s3am/operations.py", line 357, in _propagate_worker_exception
    yield
  File "/opt/s3am/local/lib/python2.7/site-packages/s3am/operations.py", line 387, in _stream_part
    part = self._upload_part( upload_id, part_num, buf )
  File "/opt/s3am/local/lib/python2.7/site-packages/s3am/operations.py", line 454, in _upload_part
    key = upload.upload_part_from_file( buf, part_num + 1, headers=headers )
  File "/opt/s3am/local/lib/python2.7/site-packages/boto/s3/multipart.py", line 260, in upload_part_from_file
    query_args=query_args, size=size)
  File "/opt/s3am/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/opt/s3am/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/opt/s3am/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/opt/s3am/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/opt/s3am/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/opt/s3am/local/lib/python2.7/site-packages/boto/connection.py", line 1030, in _mexe
    raise ex
error: [Errno 104] Connection reset by peer
```

and if left to do it's thing, eventually it ends with 

```
Traceback (most recent call last):
  File "/usr/local/bin/s3am", line 11, in <module>
    sys.exit(try_main())
  File "/opt/s3am/local/lib/python2.7/site-packages/s3am/cli.py", line 37, in try_main
    main( args )
  File "/opt/s3am/local/lib/python2.7/site-packages/s3am/cli.py", line 74, in main
    result = operation.run( )
  File "/opt/s3am/local/lib/python2.7/site-packages/s3am/operations.py", line 250, in run
    raise WorkerException( )
s3am.WorkerException
```

**Comment by hannes-ucsc** [comment]
Can you send output of `/opt/s3am/bin/pip list`

**Comment by dyollluap** [comment]
mesosbox@ip-172-31-42-19:~$ /opt/s3am/bin/pip list
boto (2.38.0)
pip (8.0.2)
pycurl (7.43.0)
s3am (1.0b1.dev49)
setuptools (20.2.2)
wheel (0.29.0)

**Comment by hannes-ucsc** [comment]
That version of s3am (1.0b1.dev49) does not have the credentials caching I implemented to address this issue.

The stable branch of cgcloud needs to be updated to install version 1.1 of s3am which will include the fix.

**Comment by hannes-ucsc** [comment]
Release [1.3.8](https://github.com/BD2KGenomics/cgcloud/releases/tag/releases%2F1.3.8) of cgcloud should fix this.

**Comment by dyollluap** [comment]
Still getting this error with cgcloud 1.3.8

mesosbox@ip-172-31-7-244:~$ /opt/s3am/bin/pip list
bd2k-python-lib (1.13.dev16)
boto (2.38.0)
pip (8.0.2)
pycurl (7.43.0)
s3am (1.1)
setuptools (20.6.7)
wheel (0.29.0)
